---
- name: detect existing Flynn CLI
  stat:
    path: "{{ flynn_cli_executable }}"
  register: existing_flynn

- name: download Flynn CLI
  when: existing_flynn.stat.exists == false
  become: true
  # The Flynn project needs to use compression _at the protocol layer_ instead.
  # Because this URL returns a gzip-compressed file, Ansible has no straightforward way to place it.
  shell: "curl -sSL -A \"`uname -sp`\" https://dl.flynn.io/cli | zcat >{{ flynn_cli_executable }}"
  args:
    executable: /bin/bash

# Removed because this Flynn now places a symlink, so Ansible dies with an error because
# we didn't provide `src`. But since Flynn makes it executable, this seems unnecessary.
# - name: Flynn CLI executable mode
#   become: true
#   file:
#     dest: "{{ flynn_cli_executable }}"
#     mode: u=rwx,g=rwx,o=rx

- name: add clusters to users
  include: user_config_cluster.yml
  when: flynn_cli_users and flynn_cli_clusters
  vars:
    username: "{{ item.0 }}"
    cluster: "{{ item.1 }}"
  with_nested:
  - "{{ flynn_cli_users }}"
  - "{{ flynn_cli_clusters }}"
