---
- name: detect existing Flynn CLI
  stat:
    path: "{{ flynn_cli_executable }}"
  register: existing_flynn

- name: download Flynn CLI
  when: existing_flynn.stat.exists == false
  become: true
  shell: "curl -sSL -A \"`uname -sp`\" https://dl.flynn.io/cli | zcat >{{ flynn_cli_executable }}"
  args:
    executable: /bin/bash

- name: add clusters to users
  include: user_config_cluster.yml
  when: flynn_cli_users and flynn_cli_clusters
  # debug: 'msg="username: {{ username }} cluster: {{ cluster }}"'
  vars:
    username: "{{ item.0 }}"
    cluster: "{{ item.1 }}"
  with_nested:
  - "{{ flynn_cli_users }}"
  - "{{ flynn_cli_clusters }}"
